#!/usr/bin/env bash
# set -vx

printhelp() {
    cat <<EOM
usage: dye [-x|-r] [color_code] "input_color"
options:
 -x [color_code]          hex to [color_code]
 -r [color_code]          rgb to [color_code]
 -h [color_code]          hsl to [color_code]
examples:
 dye -x rgb "#fff"
 dye -x rgb "#ffffff"
 dye -r hex "rgb(255, 255, 255)"
 dye -x rgb "#43fF6480"
 dye -r hex "rgba(67, 255, 100, 0.5)"
 dye -h rgb "hsl(350, 100, 100)"
 dye -h hex "hsla(350, 100, 100, 1.0)"
EOM
    exit 0
}

error() {
    printf "error: %s\n" "$1" 1>&2
    exit 2
}

hex_to_rgb() {
    local a
    # null command ':' removes all leading hashtag characters
    : "${3/\#/}"
    # if hex value is 8 characters
    if ((${#_} == 8)); then
        # convert characters to hex (see credits at bottom)
        ((r = 16#${_:0:2}, g = 16#${_:2:2}, b = 16#${_:4:2}, a = 16#${_:6:2}))
        # simple calc for alpha channel
        a=$(echo "scale=2; $a / 255" | bc)
    # else if hex value is 6 characters (no alpha channel)
    elif ((${#_} == 6)); then
        ((r = 16#${_:0:2}, g = 16#${_:2:2}, b = 16#${_:4:2}))
        a=1.0
    # else if hex value is 3 characters (minimal hex value provided)
    elif ((${#_} == 3)); then
        # if the first character still has a hashtag in it...
        if [[ ${3:0:1} != "#" ]]; then
            color="#$3"
        else
            color="$3"
        fi
        # grab out each passed value
        r="$(echo "$color" | cut -c2)"
        g="$(echo "$color" | cut -c3)"
        b="$(echo "$color" | cut -c4)"

        # and convert them to hexadecimal
        r=$(printf "%d" 0x$r$r)
        g=$(printf "%d" 0x$g$g)
        b=$(printf "%d" 0x$b$b)

        # ((r = 16#${_:0:1}, g = 16#${_:1:1}, b = 16#${_:2:1}))
        a=1.0
    else
        error "$3 is not a recognized hex color code."
    fi
    printf "%s\n" "rgba($r, $g, $b, $a)"
}

# hex_to_hsl() {}

# parse_rgb() takes rgb string to pass to rgb_to_hex()
parse_rgb() {
    local regex='^rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}[)]$|^rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}, [0-1]?.[0-9][0-9]?[)]$'
    if [[ $3 =~ $regex ]]; then
        local numbers
        numbers=$(echo "$3" | sed -n 's/.*\(([^()]*)\).*/\1/p' | sed 's/[()]//g' | sed 's/,\s/ /g')
        read -r -a rgb <<< "$numbers"
        rgb_to_hex  "${rgb[$"0"]}" "${rgb[$"1"]}" "${rgb[$"2"]}" "${rgb[$"3"]}"
    else
        error "pattern passed is not valid rgba format"
    fi
}

rgb_to_hex() {
    local a
    # if a fourth arg is provided (alpha channel)
    if [[ -n "$4" ]]; then
        # converts alpha channel to hex (see below)
        a=$(printf "%02x\n" "$(echo "scale=0; $4*255" | bc)" 2>/dev/null)
        printf "#%02x%02x%02x%s\n" "$1" "$2" "$3" "$a"
    else
        printf "#%02x%02x%02x\n" "$1" "$2" "$3"
    fi
}

# rgb_to_hsl() {}

# hsl_to_hex() {}

# hsl_to_rgb() {}

main() {
    [[ "$#" -lt 1 ]] && printhelp

    while getopts ":x:r:h:?" arg; do
        case $arg in
            x)
                if [[ "$2" == "rgb" ]]; then
                    local rgbval clipit
                    rgbval=$(hex_to_rgb "$@")
                    printf "%s\n" "$rgbval"
                    read -e -r -p "save code to clipboard?(y/n): " clipit
                    if [[ "$clipit" == "yes" || "$clipit" == "y" ]]; then
                        printf "%s" "$rgbval" | xclip -sel clip
                    fi
                # elif [[ "$2" -eq "hsl" ]]; then
                     # hex_to_hsl "$@"
                fi
                ;;
            r)
                if [[ "$2" == "hex" ]]; then
                    local hexval clipit
                    hexval=$(parse_rgb "$@")
                    printf "%s\n" "$hexval"
                    read -e -r -p "save code to clipboard?(y/n): " clipit
                    if [[ "$clipit" == "yes" || "$clipit" == "y" ]]; then
                        printf "%s" "$hexval" | xclip -sel clip
                    fi
                # elif [[ "$2" -eq "hsl" ]]; then
                     # rgb_to_hsl "$@"
                fi
                ;;
            h)
                printhelp
                # if [[ "$2" == "rgb" ]]; then
                    # hsl_to_rgb "$@"
                # elif [[ "$2" == "hex" ]]; then
                    # hsl_to_hex "$@"
                # fi
                ;;
            ?)
                printhelp
                ;;
        esac
    done
}

main "$@"

# Credits:
# Thanks go out to those who helped:

# Akash Mittal, whose article provided the original versions of hex_to_rgb() and rgb_to_hex() taken from
# https://akashmittal.com/code-example-convert-hex-color-to-rgb-rgb-to-hex-using-bash-script/

# redditor zeekar who broke down what those functions did line by line:
# https://reddit.com/r/bash/comments/zqmvz8/rgbhex_converter_syntax_how_does_this_work/

# redditor DyslexicHobo, who suggested ChatGPT, which I used to finalize the
# rgb_to_hex() function. Thank you AI overlords!
# https://openai.com/blog/chatgpt/
