#!/usr/bin/env bash
# set -vx

printhelp() {
    cat <<EOM
usage: dyetide [-x|-r] file
options:
 -x             replace all hex with rgba in file
 -r             replace all rgb with hex in file
examples:
 dyetide -x file
 dyetide -r file
EOM
    exit 0
}

error() {
    printf "error: %s\n" "$1" 1>&2
    exit 1
}

success() {
    printf "success: %s\n" "$1" 2>&1
    exit 0
}

# to be placed in install script
dependencycheck() {
    local dep missingdependencies=0
    for dep in "$@"; do
        if ! command -v "$dep" &>/dev/null; then
            error "dependency not met: $dep"
        fi
    done
    if [[ $missingdependencies -gt 0 ]]; then
        exit 1
    fi
}

replace_all_hex() {
    local filename
    filename="${2}"
    if [[ -f "$filename" ]]; then
        local rgb regex
        local allhexvalues hexvalues=()
        regex='#[0-9a-fA-F]{8}|#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3}'
        # grabs all hex values in $filename and puts them in $allhexvalues
        mapfile -t allhexvalues < <(grep -P -o "${regex}" "${filename}")

        if [[ ${#allhexvalues[@]} -eq 0 ]]; then
            error "no hex values found in $filename"
        fi

        # $hexvalues contains only unique hex values from $allhexvalues
        while IFS= read -r -d '' x; do
            hexvalues+=("$x")
        done < <(printf "%s\0" "${allhexvalues[@]}" | sort -uz)

        for hex in "${hexvalues[@]}"; do
            rgb=$(repaint -x "$hex")
            sed -i "s/ ${hex} / ${rgb} /g" "$filename"
            sed -i "s/${hex} /${rgb} /g" "$filename"
            sed -i "s/ ${hex};/ ${rgb};/g" "$filename"
            sed -i "s/${hex}/${rgb}/g" "$filename"
        done

        success "${filename}'s hex codes converted to rgba"
    else
        error "$filename not found"
    fi
}

replace_all_rgb() {
    local filename
    filename="${2}"
    if [[ -f "$filename" ]]; then
        local allrgbvalues rgbvalues rgbarr
        IFS=$'\n'
        regex='\s?rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}[)]|rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}, [0-1]?.[0-9][0-9]?[)]\s?'
        allrgbvalues=$(grep -Po "${regex}" "${filename}")

        read -d '' -r -a rgbarr <<< "${allrgbvalues}"

        if [[ ${#rgbarr[@]} -eq 0 ]]; then
            error "no rgb values found in $filename"
        fi

        while IFS= read -r -d '' x; do
            rgbvalues+=("$x")
        done < <(printf "%s\0" "${rgbarr[@]}" | sort -uz)

        for rgb in "${rgbvalues[@]}"; do
            hex=$(repaint -r "$rgb")
            sed -i "s/ ${rgb} / ${hex} /g" "$filename"
            sed -i "s/${rgb} /${hex} /g" "$filename"
            sed -i "s/ ${rgb};/ ${hex};/g" "$filename"
            sed -i "s/${rgb}/${hex} /g" "$filename"
        done

        success "${filename}'s rgba codes converted to hex"
    else
        error "$filename not found"
    fi
}

main() {
    [[ "$#" -lt 1 ]] && printhelp

    while getopts ":x:r:?" arg; do
        case $arg in
            x)
                replace_all_hex "$@"
                ;;
            r)
                replace_all_rgb "$@"
                ;;
            ?)
                printhelp
                ;;
        esac
    done
}

main "$@"
